#!/usr/bin/env node

/**
 * TCO Excel-to-JS parity gate.
 *
 * Inputs:
 *   1. The checked-in XLSX snapshot generated by extract_tco_workbook_snapshot.py.
 *   2. The current production engine source inside src/TcoCalculator.jsx.
 *
 * The runner does not maintain a handwritten copy of the TCO formulas. It
 * evaluates the production engine section extracted from TcoCalculator.jsx,
 * loads the canonical EngineRegression fixture from the workbook snapshot,
 * and compares current JS outputs against the workbook's expected values.
 *
 * Numeric tolerance is the workbook's own rule: MAX($1, 0.01%), where 0.01%
 * is 0.0001 as a decimal ratio.
 */

import fs from "node:fs";
import vm from "node:vm";

const SOURCE_PATH = "src/TcoCalculator.jsx";
const SNAPSHOT_PATH = "tests/tco-parity/workbook_snapshot.json";

function fail(message) {
  console.error(`PARITY ERROR: ${message}`);
  process.exit(1);
}

function sheetByName(snapshot, name) {
  const sheet = snapshot.sheets.find((s) => s.name === name);
  if (!sheet) fail(`Workbook snapshot is missing sheet ${name}`);
  return sheet;
}

function value(sheet, ref) {
  if (!(ref in sheet.cells)) fail(`${sheet.name}!${ref} is missing from workbook snapshot`);
  return sheet.cells[ref].value;
}

function mapWorkbookGpuClass(gpuClass) {
  return gpuClass === "B200" ? "B200-class" : gpuClass;
}

function mapWorkbookFacility(facility) {
  return facility === "Self-hosted" ? "Self-hosted (AI-ready)" : facility;
}

function parseSlashNumbers(text, expectedCount) {
  const vals = String(text).match(/-?\d+(?:\.\d+)?/g)?.map(Number) ?? [];
  if (vals.length !== expectedCount) {
    fail(`Could not parse ${expectedCount} values from workbook fixture text: ${text}`);
  }
  return vals;
}

function numericPass(actual, expected) {
  const tolerance = Math.max(1, 0.0001 * Math.max(Math.abs(expected), 1));
  return { pass: Math.abs(actual - expected) <= tolerance, tolerance };
}

const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf8"));
const regression = sheetByName(snapshot, "EngineRegression");

// Canonical fixture values come from the workbook itself, not duplicated
// expected inputs in this script.
const transition = parseSlashNumbers(value(regression, "B19"), 5);
const factors = parseSlashNumbers(value(regression, "B18"), 3);
const totalStorage = Number(value(regression, "B10"));
const fastShare = Number(value(regression, "B11"));

const fixture = {
  bill: Number(value(regression, "B5")),
  computeShare: Number(value(regression, "B6")),
  gpuClass: mapWorkbookGpuClass(value(regression, "B7")),
  trainShare: Number(value(regression, "B8")),
  odShare: Number(value(regression, "B9")),
  fastPB: totalStorage * fastShare,
  bulkPB: totalStorage * (1 - fastShare),
  growth: Number(value(regression, "B12")),
  facility: mapWorkbookFacility(value(regression, "B13")),
  powerRate: Number(value(regression, "B14")),
  util: Number(value(regression, "B15")),
  ownSys: String(value(regression, "B16")),
  tier3Hrs: Number(value(regression, "B17")),
  fNet: factors[0],
  fSw: factors[1],
  fNvaie: factors[2],
  retrofit: transition[0],
  migration: transition[1],
  dualRun: transition[2],
  redundancy: transition[3] === 1,
  residPct: transition[4] / 100,
  egressPct: 0.05,
  modelSize: "70B",
  quant: "FP8",
  horizon: 3,
  mode: "spend",
  gpuSizingCount: null,
  sourceClass: null,
  workingDayHours: null,
};

const source = fs.readFileSync(SOURCE_PATH, "utf8");
const start = source.indexOf("const RATES =");
const end = source.indexOf("/* ============ UI ============ */");
if (start < 0 || end < 0 || end <= start) {
  fail("Could not locate the production TCO engine section in TcoCalculator.jsx");
}

// The extracted production section contains pricing-provenance display
// constants that are irrelevant to calculation math but call imported helper
// functions at module initialization. Supply inert stubs so the exact engine
// source can execute without importing React/UI modules.
const prelude = `
const CLOUD_RATES_VERIFIED_AT = "test";
const ONPREM_PRICING_VERIFIED_AT = "test";
const fmtVerifiedDate = () => "test";
const stalenessOf = () => ({ days: 0, level: "current" });
`;

const engineSource = source.slice(start, end);
const sandbox = { console, __fixture: fixture, __result: null };
const execute = `${prelude}\n${engineSource}\n
const __rc = defaultsFor("AWS", __fixture.gpuClass, __fixture.ownSys);
const __r = run(__fixture, __rc);
const __storCapex = __fixture.fastPB * __rc.fastPB + __fixture.bulkPB * __rc.bulkPB;
const __storSup = (__fixture.fastPB * __rc.fastSupPB + __fixture.bulkPB * __rc.bulkSupPB) / 12;
const __opex = __r.year0OpexBreakdown;
const __cloudAdmin = (__rc.cloudFTE * __rc.cloudAdminFTE + __rc.billingSW) / 12;
const __computeSpend = __fixture.bill * __fixture.computeShare;
const __equinixOpex = __r.sysAdj * __rc.equinixMo + __storSup;
__result = {
  cloudGpuHours: __r.gpuHrs,
  blendedInstanceRate: __r.blended * __rc.gpusPerInstance,
  npf: __r.npf,
  systemsAdjusted: __r.sysAdj,
  systemsFloor: __r.sysFloor,
  computeNetworkCapex: __r.adj.capex - __storCapex,
  storageCapex: __storCapex,
  storageSupport: __storSup,
  power: __opex.power,
  otherFacility: (__opex.networking ?? 0) + (__opex.rackAmortization ?? 0),
  admin: __opex.admin,
  selectedOpex: __r.adj.opex,
  oneTime: __r.oneTime,
  residual: __r.adj.resid,
  cloudStorage: __r.cloudStorage,
  cloudAdmin: __cloudAdmin,
  cloudMonthlyTotal: __computeSpend + __r.cloudStorage + __cloudAdmin,
  equinixOpex: __equinixOpex,
  leaseView: "not entered",
  crossover: __r.crossoverMo == null ? null : "Month " + __r.crossoverMo,
};
`;

try {
  vm.runInNewContext(execute, sandbox, { filename: "TcoCalculator.engine-parity.js", timeout: 5000 });
} catch (err) {
  fail(`Production engine extraction/execution failed: ${err.stack || err}`);
}

const actual = sandbox.__result;
const checks = [
  ["Cloud GPU-hours/mo", "cloudGpuHours", "C24"],
  ["Blended rate $/instance-hr", "blendedInstanceRate", "C25"],
  ["Net Performance Factor", "npf", "C26"],
  ["Systems required, adjusted", "systemsAdjusted", "C27"],
  ["Systems required, floor", "systemsFloor", "C28"],
  ["Capex compute+network", "computeNetworkCapex", "C29"],
  ["Capex storage", "storageCapex", "C30"],
  ["Storage support $/mo", "storageSupport", "C31"],
  ["Power $/mo", "power", "C32"],
  ["Other facility $/mo", "otherFacility", "C33"],
  ["Admin $/mo", "admin", "C34"],
  ["Selected opex $/mo", "selectedOpex", "C35"],
  ["One-time costs", "oneTime", "C36"],
  ["Residual credit", "residual", "C37"],
  ["Cloud storage + egress $/mo", "cloudStorage", "C38"],
  ["Cloud admin $/mo", "cloudAdmin", "C39"],
  ["Cloud monthly total", "cloudMonthlyTotal", "C40"],
  ["Equinix opex option $/mo", "equinixOpex", "C41"],
  ["Lease view", "leaseView", "C42"],
  ["Crossover month", "crossover", "C43"],
];

let failed = 0;
console.log("TCO Excel-to-JS parity: canonical EngineRegression fixture");
console.log(`Workbook source: ${snapshot.source}`);
for (const [label, key, expectedCell] of checks) {
  const expected = value(regression, expectedCell);
  const got = actual[key];
  let pass;
  let detail = "";
  if (typeof expected === "number") {
    const result = numericPass(Number(got), expected);
    pass = Number.isFinite(Number(got)) && result.pass;
    detail = `tol=${result.tolerance}`;
  } else {
    pass = got === expected;
  }
  if (!pass) failed += 1;
  console.log(`${pass ? "PASS" : "FAIL"} | ${label} | JS=${String(got)} | Excel=${String(expected)}${detail ? ` | ${detail}` : ""}`);
}

console.log(`\nResult: ${checks.length - failed}/${checks.length} checks passed.`);
if (failed) process.exit(1);
