// Source-verified technical model records that are intentionally NOT yet part
// of the customer-facing MODEL_REGISTRY. These records are methodology inputs,
// not activation. A model stays staged until its sequence-state memory contract,
// sizing behavior, product policy, Advisor behavior, and browser regressions all
// pass their activation gates.

export const STAGED_TECHNICAL_MODEL_REGISTRY = Object.freeze([
  {
    id: "qwen3.8-27b",
    legacyIds: [],
    label: "Qwen3.8 27B",
    architectureType: "dense",
    totalParamsB: 27,
    activeParamsB: 27,
    layers: 64,
    contextLength: 262144,
    modalities: ["text", "image", "video"],
    sequenceStateType: "deltanet-attention-hybrid",
    linearAttentionLayers: 48,
    fullAttentionLayers: 16,
    fullAttentionKvHeads: 4,
    fullAttentionHeadDim: 256,
    linearKeyHeads: 16,
    linearKeyHeadDim: 128,
    linearValueHeads: 48,
    linearValueHeadDim: 128,
    linearConvKernel: 4,
    recurrentStateBytesPerElement: 4,
    convolutionStateBytesPerElement: 2,
    status: "VERIFIED",
    architectureSource: "https://huggingface.co/Qwen/Qwen3.8-27B/blob/main/config.json",
    stateImplementationSource: "https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen3_5/modeling_qwen3_5.py",
    stateSizingNote: "Qwen3.8 uses a 3:1 Gated DeltaNet/full-attention pattern. Recurrent DeltaNet state is fixed-size per sequence and sourced as float32; full-attention layers retain token-growing KV state. Convolution state is conservatively treated as BF16/model dtype.",
  },
  {
    id: "deepseek-v4-flash-0731",
    legacyIds: [],
    label: "DeepSeek V4 Flash 0731",
    architectureType: "moe",
    totalParamsB: 304,
    activeParamsB: 13,
    numExperts: 256,
    numSharedExperts: 1,
    routedExpertsPerToken: 6,
    activeExpertsPerToken: 7,
    layers: 43,
    contextLength: 1048576,
    modalities: ["text"],
    sequenceStateType: "deepseek-v4-compressed-attention",
    sharedKvHeads: 1,
    sharedKvHeadDim: 512,
    slidingWindow: 128,
    slidingOnlyLayers: 2,
    csaLayers: 21,
    hcaLayers: 20,
    csaCompressRate: 4,
    hcaCompressRate: 128,
    indexHeadDim: 128,
    compressionAuxBytesPerElement: 2,
    status: "VERIFIED",
    architectureSource: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash-0731/blob/main/config.json",
    stateImplementationSource: "https://github.com/huggingface/transformers/blob/main/src/transformers/models/deepseek_v4/modular_deepseek_v4.py",
    stateSizingNote: "All 43 attention layers use a shared K=V sliding-window branch. Twenty-one CSA layers add compressor + indexer long-range state at 4:1 compression; twenty HCA layers add compressor long-range state at 128:1 compression. Compression buffers/overlap are treated conservatively at BF16/model dtype rather than assumed quantizable by the generic KV-cache precision control.",
  },
  {
    id: "deepseek-v4-pro-0813",
    legacyIds: [],
    label: "DeepSeek V4 Pro 0813",
    architectureType: "moe",
    totalParamsB: 1650,
    activeParamsB: 49,
    numExperts: 384,
    numSharedExperts: 1,
    routedExpertsPerToken: 6,
    activeExpertsPerToken: 7,
    layers: 61,
    contextLength: 1048576,
    modalities: ["text"],
    sequenceStateType: "deepseek-v4-compressed-attention",
    sharedKvHeads: 1,
    sharedKvHeadDim: 512,
    slidingWindow: 128,
    slidingOnlyLayers: 0,
    csaLayers: 30,
    hcaLayers: 31,
    csaCompressRate: 4,
    hcaCompressRate: 128,
    indexHeadDim: 128,
    compressionAuxBytesPerElement: 2,
    status: "VERIFIED",
    architectureSource: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro-0813/blob/main/config.json",
    stateImplementationSource: "https://github.com/huggingface/transformers/blob/main/src/transformers/models/deepseek_v4/modular_deepseek_v4.py",
    stateSizingNote: "All 61 attention layers use a shared K=V sliding-window branch. Thirty CSA layers add compressor + indexer long-range state at 4:1 compression; thirty-one HCA layers add compressor long-range state at 128:1 compression. Compression buffers/overlap are treated conservatively at BF16/model dtype rather than assumed quantizable by the generic KV-cache precision control.",
  },
  {
    id: "nemotron-3-super-120b-a12b",
    legacyIds: [],
    label: "NVIDIA Nemotron 3 Super 120B-A12B FP8",
    architectureType: "hybrid",
    totalParamsB: 120,
    activeParamsB: 12,
    layers: 88,
    contextLength: 262144,
    advertisedExtendedContextLength: 1000000,
    modalities: ["text"],
    sequenceStateType: "mamba-attention-hybrid",
    mambaLayers: 40,
    attentionLayers: 8,
    moeLayers: 40,
    attentionKvHeads: 2,
    attentionHeadDim: 128,
    mambaNumHeads: 128,
    mambaHeadDim: 64,
    mambaStateSize: 128,
    mambaGroups: 8,
    mambaConvKernel: 4,
    recurrentStateBytesPerElement: 4,
    convolutionStateBytesPerElement: 2,
    status: "VERIFIED",
    architectureSource: "https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8/blob/main/config.json",
    stateImplementationSource: "https://github.com/huggingface/transformers/blob/main/src/transformers/models/nemotron_h/modeling_nemotron_h.py",
    stateSizingNote: "The verified 88-layer hybrid pattern contains 40 Mamba layers, 40 MoE layers, and 8 attention layers. Mamba SSM state is fixed-size per sequence and float32; convolution state is conservatively BF16/model dtype; only the 8 attention layers contribute token-growing KV state. The config exposes 262,144 max positions while the model card advertises up to 1M, so sizing uses the config value until that product-level context contract is reconciled.",
  },
]);

const STAGED_BY_ID = new Map(STAGED_TECHNICAL_MODEL_REGISTRY.map((model) => [model.id, model]));

export function getStagedTechnicalModelById(id) {
  return id ? STAGED_BY_ID.get(id) || null : null;
}
